apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    meta.helm.sh/release-name: {{ $.Release.Name | quote }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app: monitoring
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: envoy-stats
    helm.sh/chart: {{ .Chart.AppVersion }}
    release: monitoring
  name: istio
  namespace: {{ .Release.Namespace }}
spec:
  groups:
  - name: "istio.recording-rules"
    interval: {{ .Values.prometheus.recordingRules.interval }}
    rules:
    - record: "istio_requests_total"
      expr: |
        sum without(instance) (workload:istio_requests_total)
    - record: "istio_request_duration_milliseconds_count"
      expr: |
        sum without(instance) (workload:istio_request_duration_milliseconds_count)
    - record: "istio_request_duration_milliseconds_sum"
      expr: |
        sum without(instance) (workload:istio_request_duration_milliseconds_sum)
    - record: "istio_request_duration_milliseconds_bucket"
      expr: |
        sum without(instance) (workload:istio_request_duration_milliseconds_bucket)
    - record: "istio_request_bytes_count"
      expr: |
        sum without(instance) (workload:istio_request_bytes_count)
    - record: "istio_request_bytes_sum"
      expr: |
        sum without(instance) (workload:istio_request_bytes_sum)
    - record: "istio_request_bytes_bucket"
      expr: |
        sum without(instance) (workload:istio_request_bytes_bucket)
    - record: "istio_response_bytes_count"
      expr: |
        sum without(instance) (workload:istio_response_bytes_count)
    - record: "istio_response_bytes_sum"
      expr: |
        sum without(instance) (workload:istio_response_bytes_sum)
    - record: "istio_response_bytes_bucket"
      expr: |
        sum without(instance) (workload:istio_response_bytes_bucket)
    - record: "istio_tcp_connections_opened_total"
      expr: |
        sum without(instance) (workload:istio_tcp_connections_opened_total)
    - record: "istio_tcp_connections_closed_total"
      expr: |
        sum without(instance) (workload:istio_tcp_connections_opened_total)
    - record: "istio_tcp_sent_bytes_total_count"
      expr: |
        sum without(instance) (workload:istio_tcp_sent_bytes_total_count)
    - record: "istio_tcp_sent_bytes_total_sum"
      expr: |
        sum without(instance) (workload:istio_tcp_sent_bytes_total_sum)
    - record: "istio_tcp_sent_bytes_total_bucket"
      expr: |
        sum without(instance) (workload:istio_tcp_sent_bytes_total_bucket)
    - record: "istio_tcp_received_bytes_total_count"
      expr: |
        sum without(instance) (workload:istio_tcp_received_bytes_total_count)
    - record: "istio_tcp_received_bytes_total_sum"
      expr: |
        sum without(instance) (workload:istio_tcp_received_bytes_total_sum)
    - record: "istio_tcp_received_bytes_total_bucket"
      expr: |
        sum without(instance) (workload:istio_tcp_received_bytes_total_bucket)